language: node_js
node_js:
  - '12'
  - '10'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
env:
  - CXX=g++-4.9
before_install:
  - npm explore npm -g -- npm install node-gyp@latest
